### PR TITLE
Update version of dependencies

### PR DESCRIPTION
**Pull request by JakobBenz**
### Version Update

Update of all dependencies to the most recent version (Spring & Spring Boot were 2016 versions) except for `spring-data-mongodb`: 3.0.2 does not work, but 2.2.9 does and is from June 2020, so it should be fine.

### CODE REVIEW

**Comment by schneijan** [comment]
Sorry for the late reply. The PR looks fine for me, the MBP starts and runs and I haven't been able to spot any issues yet.

**Review by schneijan — COMMENTED** [review]
@JakobBenz Unfortunately the swagger UI for the REST Api seems to be broken. Formerly it was available at http://.../swagger-ui.html (see links in the settings), but it does not seem to work anymore after the dependency update.

**Comment by JakobBenz** [comment]
@schneijan The Swagger UI is now available again - please have a final check and then merge.

**Comment by schneijan** [comment]
As far as I can see there are unfortunately problems with login after the version update. After logout, I am unable to login again and my browser (Chromium-based as well as Edge) shows a basic authentication prompt that should not appear.

**Comment by hirmerpl** [comment]
Please resolve conflicts and move forward with the merge.

**Comment by schneijan** [comment]
This branch is stale and implicitly included in PRs #482  and #483

**Pull request closed without merging**
