### PR TITLE
Delete icons

### LINKED ISSUE #344: Use the 'Delete Icon' (trash can) instead of the text 'Delete' for buttons
we need to standardize our Delete button, for this reason we are going  to use from now on only the trash can

image

Places we need to update:

image

### PR DESCRIPTION
**Pull request by schneijan**
This PR changes the delete button of all entities to delete icons.

Closes #344

### CODE REVIEW

**Comment by tatianegava** [comment]
Hi @schneijan,
We should use in all places where there is a delete function the icon: **trash can**. Not the word delete.

And here we can only show the trash can, without the writing:
image

**Comment by schneijan** [comment]
In my opinion it is reasonable to preserve the text for the group delete button, because otherwise it wouldn't be clear what can be deleted, especially due to the similarity to the delete button for each condition.

**Comment by tatianegava** [comment]
> In my opinion it is reasonable to preserve the text for the group delete button, because otherwise it wouldn't be clear what can be deleted, especially due to the similarity to the delete button for each condition.

You are write. Can we leave only Group and take out "delete"?

**Comment by hirmerpl** [comment]
Instead of putting the word "DELETE", we should put the trash can icon, since you also have the share icon right next to it and not the word "SHARE".

**Comment by schneijan** [comment]
> Instead of putting the word "DELETE", we should put the trash can icon, since you also have the share icon right next to it and not the word "SHARE".

I totally agree for the entities, but (as discussed above) I think for the operator groups in the rule conditions tool this would be hard to understand.

> You are write. Can we leave only Group and take out "delete"?
I think this is a good solution, changed it

**Pull request merged**
