### PR TITLE
Fixes for user management

### LINKED ISSUE #516: Problems in the user view
Problems:
* As an Admin, the button to access users view is missing. 
image
* As an Admin, accessing the users view through the known URL (http://localhost:8080/MBP/view/users), the view seems to be broken. As a normal user, the same is shown as bellow.
image

### PR DESCRIPTION
**Pull request by schneijan**
Brings back the user management with options for setting admins, changing passwords etc.

Closes #516

### CODE REVIEW

**Comment by ana-silva** [comment]
Hi @schneijan, the user management view is working again, changing passwords worked as well.
However, i was able to delete the standard users and also the Admin. I think it should not be possible to delete the admin and the standard users.

After deleting the database in the mongoDB, I restarted the MBP. The users were back, however the option to change the password for the Admin was gone 🤨 

image

**Comment by schneijan** [comment]
Hi,

thanks for your feedback. :-) I added some further improvements to the user mangement system and also fixed the issue you described.

**Comment by ana-silva** [comment]
@schneijan can you please solve the conflicts? we tested the branch and the problems were solved, therefore we would like to merge the PR

**Comment by schneijan** [comment]
Hi,

sorry for the inconvience. My local git installation did not detect any merge conflicts and merged the branchs now automatically (probably a different git configuration). Merge should now be possible. :-)

**Pull request merged**
