### PR TITLE
Cascade delete with confirm

### LINKED ISSUE #29: Deleting a device/adapter should also delete related sensors and actuators

### LINKED ISSUE #30: After deletion of an adapter, deploy is still possible
Verify what happens in the backend

### PR DESCRIPTION
**Pull request by schneijan**
This PR contains the following changes:
- All new created actuators and sensors now only refer to the corresponding adapters and devices, they are no longer saved as a deep copy.
- When deleting an adapter or a device, all actuators and all sensors which make use of them are deleted as well.
- On the web interface, the user now needs to confirm his decision if he tries to delete an adapter, device, sensor or actuator. The [SweetAlert2](https://sweetalert2.github.io) plugin is used for this purpose. For adapters and devices, all components (actuators and sensors) that make use of them are resolved and displayed to the user. This way, he can make sure to not delete an actuator or sensor by accident.
- A notification system (see NotificationService) is introduced by using the [bootstrap notify plugin](http://bootstrap-notify.remabledesigns.com). Currently it is used for the deletion of adapters, devices, actuators and sensors.

Closes #29 
Closes #30

### CODE REVIEW

**Comment by hirmerpl** [comment]
What I am missing is a warning like "Warning, deleting this adapter also leads to deletion of all corresponding sensors or actuators".

**Comment by schneijan** [comment]
> What I am missing is a warning like "Warning, deleting this adapter also leads to deletion of all corresponding sensors or actuators".

Such a warning is already displayed when there are actual actuators/sensors that will be affected by the deletion of the adapter/device:
image

However, the cascade delete does only work for new actuators and sensors. For old actuators end sensors, there is still a full deep copy stored in the mongo db and thus they won't be deleted when their adapters or devices are deleted.

**Comment by hirmerpl** [comment]
Looks good, maybe delete button should be in red :-)

**Comment by schneijan** [comment]
Done :-)

**Pull request merged**
