### PR TITLE
Environment modelling tool rework

### LINKED ISSUE #186: [IoT-Modelling-Tool] Import / Export of Environment Models as JSON
It should be possible to import and export IoT environment models as JSON. This concerns the REST API as well as the User Interface.

### LINKED ISSUE #193: [IoT-Modelling-Tool] Adjust color coding
Currently, the color coding is as follows: Green = Devices etc. registered, Yellow = Devices etc. deployed, Red = error. 

This should be changed to:
Yellow = Devices etc. registered, Blue = Devices etc. deployed, Red = error.

### LINKED ISSUE #204: [IoT-Modelling-Tool] Rework user management of IoT models
At the moment a username is stored for each IoT model. This should be replaced with user IDs.

### LINKED ISSUE #214: [IoT-Modelling-Tool] Add all device types available in the device registration
Missing device types:

- [ ] Gateway
- [ ] NodeMCU

Also add types for sensors and actuators in case there is something in the registration and is missing in the modeling tool.

### LINKED ISSUE #237: [IoT-Modelling-Tool] Extract tool to directive
The IoT Modelling Tool needs to be extracted in its own directive in order to encapsulate it from page controllers.

### LINKED ISSUE #238: [IoT-Modelling-Tool] Rename model entities
Model entities should be renamed to something like _env-models_ in order to make them distinguishable from other model types.

### LINKED ISSUE #239: [IoT-Modelling-Tool] Display list of available models
A list of all available models should be displayed in the style of the other MBP entity lists.

### LINKED ISSUE #240: [IoT-Modelling-Tool] Fix model counter on home page
The model counter on the home page does not work. In fact, it is hard-coded to display a value of 0.

### LINKED ISSUE #242: [IoT-Modelling-Tool] Preserve aspect ratio
The aspect ratio of most components should be preserved, in order to avoid big empty white boxes.

### LINKED ISSUE #243: [IoT-Modelling-Tool] Fix position of deletion button
The cross icon that may be used for deleting placed components should always be deisplayed at a fixed position, regardless of rotation and resizing.

### LINKED ISSUE #244: [IoT-Modelling-Tool] Adjust component size
Some component icons are wrapped into a container that is too big, leading to a lot of white space.

### LINKED ISSUE #245: [IoT-Modelling-Tool] Animate resizing of rooms
Rooms are resized automatically when dropped on the canvas. This is bad UX.

### LINKED ISSUE #247: [IoT-Modelling-Tool] Elements jump around on resizing
When resizing an element in the canvas, there is a small and sudden "jump" that resizes the element unexpectedly.

### LINKED ISSUE #248: [IoT-Modelling-Tool] Make resizing more intuitive
Resizing of drawed components should be more intuitive, e.g. by displaying resizing handlers.

### LINKED ISSUE #249: [IoT-Modelling-Tool] Resizing only after focusing
Resizing of elements should only be possible after the user clicked on the corresponding element.

### LINKED ISSUE #259: [IoT-Modelling-Tool] Add menu bar
We need a menu bar for save, copy, paste, cut, import, export, ...

### LINKED ISSUE #260: [IoT-Modelling-Tool] Marking rectangle
It should be possible to mark multiple elements at once using some kind of "marking rectangle" that appears when dragging the mouse.

### LINKED ISSUE #261: [IoT-Modelling-Tool] Better marking highlight
Marked elements need to be highlighted in a more comprehensible way, e.g. like its done at draw.io

### LINKED ISSUE #262: [IoT-Modelling-Tool] Replace right sidebar with modals
The side bar on the right-hand side that displays details information about sensors/devices should be replaced by modals popping up.

### LINKED ISSUE #278: Enable auditing of user entities
We should enable auditing for all user entities, in order to record creation dates, modification dates, creators, modificators etc.

MongoDB Auditing should be sufficient to achieve this.

### PR DESCRIPTION
**Pull request by schneijan**
Includes a full rework of the environment modelling tool, in terms of the frontend as well of the backend. Management of models and actions like registration and deployment are now handled by the backend instead of the frontend.

Due to the complexity of the environment model, it is very likely that this PR contains bugs and undesired behaviour. Thus, extensive testing and checking is required.

Closes #186 
Closes #193 
Closes #204 
Closes #214 
Closes #237 
Closes #238 
Closes #239 
Closes #240 
Ckises #241 
Closes #242 
Closes #243 
Closes #244 
Closes #245 
Closes #247 
Closes #248 
Closes #249 
Closes #259
Closes #260 
Closes #261 
Closes #262 
Closes #278

### CODE REVIEW

**Comment by hirmerpl** [comment]
Unfortunately, the PR can currently not be run: http://192.168.221.194:8888/deploy/PR-300/
There seams to be an internal server error.

**Comment by hirmerpl** [comment]
Exporting a model and importing in a blank one does not work after providing the device and sensor properties. Check the following model: http://192.168.221.194:8888/deploy/env_model_rework/view/env-models

To reproduce Export this model, create a new one and import it. 

{"nodes":[{"type":"Raspberry Pi","nodeType":"device","elementId":"node1","clsName":"window device raspberry-pi-device ui-draggable ui-draggable-handle jtk-node jtk-droppable jtk-endpoint-anchor jtk-connected","left":124.60003662109375,"top":172.39999389648438,"width":50,"height":50,"details":{"name":"My-Comp","ipAddress":"192.168.221.140","username":"ubuntu","password":"","rsaKey":""},"angle":0},{"type":"Temperature","nodeType":"sensor","elementId":"node2","clsName":"window sensor temperature-sensor ui-draggable ui-draggable-handle jtk-node jtk-droppable jtk-endpoint-anchor jtk-connected","left":322,"top":183.00003051757812,"width":50,"height":50,"details":{"name":"test","adapter":"5ebe54aaca2b0d52259a4b30"}}],"connections":[{"id":"con_5","sourceId":"node1","targetId":"node2","label":"NAME","labelVisible":false}],"numberOfElements":2,"elementIdCount":2}

**Comment by hirmerpl** [comment]
Also, start does not work for me, however, this could be a problem with operator, broker etc.

Please verify my comments using the created model "Hallo Test"

**Comment by schneijan** [comment]
Merge conflicts are resolved now

**Pull request merged**
